package main

// Code generated by github.com/tinylib/msgp DO NOT EDIT.

import (
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *StructV1) DecodeMsg(dc *msgp.Reader) (err error) {
	var zb0001 uint32
	zb0001, err = dc.ReadArrayHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	if zb0001 != 2 {
		err = msgp.ArrayError{Wanted: 2, Got: zb0001}
		return
	}
	z.A, err = dc.ReadUint32()
	if err != nil {
		err = msgp.WrapError(err, "A")
		return
	}
	z.B, err = dc.ReadUint32()
	if err != nil {
		err = msgp.WrapError(err, "B")
		return
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z StructV1) EncodeMsg(en *msgp.Writer) (err error) {
	// array header, size 2
	err = en.Append(0x92)
	if err != nil {
		return
	}
	err = en.WriteUint32(z.A)
	if err != nil {
		err = msgp.WrapError(err, "A")
		return
	}
	err = en.WriteUint32(z.B)
	if err != nil {
		err = msgp.WrapError(err, "B")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z StructV1) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// array header, size 2
	o = append(o, 0x92)
	o = msgp.AppendUint32(o, z.A)
	o = msgp.AppendUint32(o, z.B)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *StructV1) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadArrayHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	if zb0001 != 2 {
		err = msgp.ArrayError{Wanted: 2, Got: zb0001}
		return
	}
	z.A, bts, err = msgp.ReadUint32Bytes(bts)
	if err != nil {
		err = msgp.WrapError(err, "A")
		return
	}
	z.B, bts, err = msgp.ReadUint32Bytes(bts)
	if err != nil {
		err = msgp.WrapError(err, "B")
		return
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z StructV1) Msgsize() (s int) {
	s = 1 + msgp.Uint32Size + msgp.Uint32Size
	return
}

// DecodeMsg implements msgp.Decodable
func (z *StructV2) DecodeMsg(dc *msgp.Reader) (err error) {
	var zb0001 uint32
	zb0001, err = dc.ReadArrayHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	if zb0001 != 3 {
		err = msgp.ArrayError{Wanted: 3, Got: zb0001}
		return
	}
	z.A, err = dc.ReadUint32()
	if err != nil {
		err = msgp.WrapError(err, "A")
		return
	}
	z.B, err = dc.ReadUint32()
	if err != nil {
		err = msgp.WrapError(err, "B")
		return
	}
	z.C, err = dc.ReadUint32()
	if err != nil {
		err = msgp.WrapError(err, "C")
		return
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z StructV2) EncodeMsg(en *msgp.Writer) (err error) {
	// array header, size 3
	err = en.Append(0x93)
	if err != nil {
		return
	}
	err = en.WriteUint32(z.A)
	if err != nil {
		err = msgp.WrapError(err, "A")
		return
	}
	err = en.WriteUint32(z.B)
	if err != nil {
		err = msgp.WrapError(err, "B")
		return
	}
	err = en.WriteUint32(z.C)
	if err != nil {
		err = msgp.WrapError(err, "C")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z StructV2) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// array header, size 3
	o = append(o, 0x93)
	o = msgp.AppendUint32(o, z.A)
	o = msgp.AppendUint32(o, z.B)
	o = msgp.AppendUint32(o, z.C)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *StructV2) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadArrayHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	if zb0001 != 3 {
		err = msgp.ArrayError{Wanted: 3, Got: zb0001}
		return
	}
	z.A, bts, err = msgp.ReadUint32Bytes(bts)
	if err != nil {
		err = msgp.WrapError(err, "A")
		return
	}
	z.B, bts, err = msgp.ReadUint32Bytes(bts)
	if err != nil {
		err = msgp.WrapError(err, "B")
		return
	}
	z.C, bts, err = msgp.ReadUint32Bytes(bts)
	if err != nil {
		err = msgp.WrapError(err, "C")
		return
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z StructV2) Msgsize() (s int) {
	s = 1 + msgp.Uint32Size + msgp.Uint32Size + msgp.Uint32Size
	return
}
